import { MenuItem } from './model';

export const menus: MenuItem[] = [
    {
        id: '1',
        name: 'espresso',
        nameTh: 'เอสเพรสโซ่',
        categoryName: 'กาแฟ',
        imageUrl: 'https://img.freepik.com/free-vector/coffee-love-foam-with-beans-cartoon-icon-illustration_138676-2575.jpg?t=st=1694105026~exp=1694105626~hmac=593436c074ea22bb01f82537139f071ce8907998b821c532d509dc1f45db8fd1',
        basePrice: 30,
        options: [
            {
                id: '1',
                type: 'SINGLE',
                name: 'process',
                nameTh: 'รูปแบบ',
                calculateType: 'BASE',
                choices: [
                    {
                        id: '1',
                        name: 'hot',
                        nameTh: 'ร้อน',
                        price: 30,
                        default: true,
                    },
                    {
                        id: '2',
                        name: 'iced',
                        nameTh: 'เย็น',
                        price: 40,
                        default: false,
                    },
                    {
                        id: '3',
                        name: 'frappe',
                        nameTh: 'ปั่น',
                        price: 45,
                        default: false,
                    },
                ],
            },
            {
                id: '2',
                type: 'SINGLE',
                name: 'sweetness',
                nameTh: 'ความหวาน',
                calculateType: 'NO',
                choices: [
                    {
                        id: '1',
                        name: 'No Sweet',
                        nameTh: 'ไม่หวาน',
                        price: 0,
                        default: false,
                    },
                    {
                        id: '2',
                        name: 'Less Sweet',
                        nameTh: 'หวานน้อย',
                        price: 0,
                        default: false,
                    },
                    {
                        id: '3',
                        name: 'Normal',
                        nameTh: 'หวานปกติ',
                        price: 0,
                        default: true,
                    },
                    {
                        id: '4',
                        name: 'Extra Sweet',
                        nameTh: 'หวานมาก',
                        price: 0,
                        default: false,
                    },
                ],
            },
            {
                id: '3',
                type: 'SINGLE',
                name: 'additionalShot',
                nameTh: 'จำนวน shot กาแฟ',
                calculateType: 'ADDITIONAL',
                choices: [
                    {
                        id: '1',
                        name: 'NO',
                        nameTh: 'ไม่เพิ่ม',
                        price: 0,
                        default: true,
                    },
                    {
                        id: '2',
                        name: 'เพิ่ม 1 Shot',
                        nameTh: 'เพิ่ม 1 Shot',
                        price: 10,
                        default: false,
                    },
                ],
            },
        ],
    },
    {
        id: '2',
        name: 'americano',
        nameTh: 'อเมริกาโน่',
        categoryName: 'กาแฟ',
        imageUrl: 'https://img.freepik.com/free-vector/coffee-love-foam-with-beans-cartoon-icon-illustration_138676-2575.jpg?t=st=1694105026~exp=1694105626~hmac=593436c074ea22bb01f82537139f071ce8907998b821c532d509dc1f45db8fd1',
        basePrice: 30,
        options: [
            {
                id: '1',
                type: 'SINGLE',
                name: 'process',
                nameTh: 'รูปแบบ',
                calculateType: 'BASE',
                choices: [
                    {
                        id: '1',
                        name: 'hot',
                        nameTh: 'ร้อน',
                        price: 30,
                        default: true,
                    },
                    {
                        id: '2',
                        name: 'iced',
                        nameTh: 'เย็น',
                        price: 40,
                        default: false,
                    },
                    {
                        id: '3',
                        name: 'frappe',
                        nameTh: 'ปั่น',
                        price: 45,
                        default: false,
                    },
                ],
            },
            {
                id: '2',
                type: 'SINGLE',
                name: 'sweetness',
                nameTh: 'ความหวาน',
                calculateType: 'NO',
                choices: [
                    {
                        id: '1',
                        name: 'No Sweet',
                        nameTh: 'ไม่หวาน',
                        price: 0,
                        default: true,
                    },
                    {
                        id: '2',
                        name: 'Extra Sweet',
                        nameTh: 'เพิ่มหวาน',
                        price: 0,
                        default: false,
                    },
                ],
            },
            {
                id: '3',
                type: 'SINGLE',
                name: 'additionalShot',
                nameTh: 'จำนวน shot กาแฟ',
                calculateType: 'ADDITIONAL',
                choices: [
                    {
                        id: '1',
                        name: 'NO',
                        nameTh: 'ไม่เพิ่ม',
                        price: 0,
                        default: true,
                    },
                    {
                        id: '2',
                        name: 'Add 1 Shot',
                        nameTh: 'เพิ่ม 1 Shot',
                        price: 10,
                        default: false,
                    },
                ],
            },
        ],
    },
    {
        id: '3',
        name: 'cappuccino',
        nameTh: 'คาปูชิโน่',
        categoryName: 'กาแฟ',
        imageUrl: 'https://img.freepik.com/free-vector/coffee-love-foam-with-beans-cartoon-icon-illustration_138676-2575.jpg?t=st=1694105026~exp=1694105626~hmac=593436c074ea22bb01f82537139f071ce8907998b821c532d509dc1f45db8fd1',
        basePrice: 30,
        options: [
            {
                id: '1',
                type: 'SINGLE',
                name: 'process',
                nameTh: 'รูปแบบ',
                calculateType: 'BASE',
                choices: [
                    {
                        id: '1',
                        name: 'hot',
                        nameTh: 'ร้อน',
                        price: 30,
                        default: true,
                    },
                    {
                        id: '2',
                        name: 'iced',
                        nameTh: 'เย็น',
                        price: 40,
                        default: false,
                    },
                    {
                        id: '3',
                        name: 'frappe',
                        nameTh: 'ปั่น',
                        price: 45,
                        default: false,
                    },
                ],
            },
            {
                id: '2',
                type: 'SINGLE',
                name: 'sweetness',
                nameTh: 'ความหวาน',
                calculateType: 'NO',
                choices: [
                    {
                        id: '1',
                        name: 'No Sweet',
                        nameTh: 'ไม่หวาน',
                        price: 0,
                        default: false,
                    },
                    {
                        id: '2',
                        name: 'Less Sweet',
                        nameTh: 'หวานน้อย',
                        price: 0,
                        default: false,
                    },
                    {
                        id: '3',
                        name: 'Normal',
                        nameTh: 'หวานปกติ',
                        price: 0,
                        default: true,
                    },
                    {
                        id: '4',
                        name: 'Extra Sweet',
                        nameTh: 'หวานมาก',
                        price: 0,
                        default: false,
                    },
                ],
            },
            {
                id: '3',
                type: 'SINGLE',
                name: 'additionalShot',
                nameTh: 'จำนวน shot กาแฟ',
                calculateType: 'ADDITIONAL',
                choices: [
                    {
                        id: '1',
                        name: 'NO',
                        nameTh: 'ไม่เพิ่ม',
                        price: 0,
                        default: true,
                    },
                    {
                        id: '2',
                        name: 'เพิ่ม 1 Shot',
                        nameTh: 'เพิ่ม 1 Shot',
                        price: 10,
                        default: false,
                    },
                ],
            },
        ],
    },
    {
        id: '4',
        name: 'latte',
        nameTh: 'ลาเต้',
        categoryName: 'กาแฟ',
        imageUrl: 'https://img.freepik.com/free-vector/coffee-love-foam-with-beans-cartoon-icon-illustration_138676-2575.jpg?t=st=1694105026~exp=1694105626~hmac=593436c074ea22bb01f82537139f071ce8907998b821c532d509dc1f45db8fd1',
        basePrice: 30,
        options: [
            {
                id: '1',
                type: 'SINGLE',
                name: 'process',
                nameTh: 'รูปแบบ',
                calculateType: 'BASE',
                choices: [
                    {
                        id: '1',
                        name: 'hot',
                        nameTh: 'ร้อน',
                        price: 30,
                        default: true,
                    },
                    {

                        id: '2',
                        name: 'iced',
                        nameTh: 'เย็น',
                        price: 40,
                        default: false,
                    },
                    {
                        id: '3',
                        name: 'frappe',
                        nameTh: 'ปั่น',
                        price: 45,
                        default: false,
                    },
                ],
            },
            {
                id: '2',
                type: 'SINGLE',
                name: 'sweetness',
                nameTh: 'ความหวาน',
                calculateType: 'NO',
                choices: [
                    {
                        id: '1',
                        name: 'No Sweet',
                        nameTh: 'ไม่หวาน',
                        price: 0,
                        default: false,
                    },
                    {
                        id: '2',
                        name: 'Less Sweet',
                        nameTh: 'หวานน้อย',
                        price: 0,
                        default: false,
                    },
                    {
                        id: '3',
                        name: 'Normal',
                        nameTh: 'หวานปกติ',
                        price: 0,
                        default: true,
                    },
                    {
                        id: '4',
                        name: 'Extra Sweet',
                        nameTh: 'หวานมาก',
                        price: 0,
                        default: false,
                    },
                ],
            },
            {
                id: '3',
                type: 'SINGLE',
                name: 'additionalShot',
                nameTh: 'จำนวน shot กาแฟ',
                calculateType: 'ADDITIONAL',
                choices: [
                    {
                        id: '1',
                        name: 'NO',
                        nameTh: 'ไม่เพิ่ม',
                        price: 0,
                        default: true,
                    },
                    {
                        id: '2',
                        name: 'เพิ่ม 1 Shot',
                        nameTh: 'เพิ่ม 1 Shot',
                        price: 10,
                        default: false,
                    },
                ],
            },
        ],
    },
    {
        id: '5',
        name: 'mocha',
        nameTh: 'มอคค่า',
        categoryName: 'กาแฟ',
        imageUrl: 'https://img.freepik.com/free-vector/coffee-love-foam-with-beans-cartoon-icon-illustration_138676-2575.jpg?t=st=1694105026~exp=1694105626~hmac=593436c074ea22bb01f82537139f071ce8907998b821c532d509dc1f45db8fd1',
        basePrice: 30,
        options: [
            {
                id: '1',
                type: 'SINGLE',
                name: 'process',
                nameTh: 'รูปแบบ',
                calculateType: 'BASE',
                choices: [
                    {
                        id: '1',
                        name: 'hot',
                        nameTh: 'ร้อน',
                        price: 30,
                        default: true,
                    },
                    {

                        id: '2',
                        name: 'iced',
                        nameTh: 'เย็น',
                        price: 40,
                        default: false,
                    },
                    {
                        id: '3',
                        name: 'frappe',
                        nameTh: 'ปั่น',
                        price: 45,
                        default: false,
                    },
                ],
            },
            {
                id: '2',
                type: 'SINGLE',
                name: 'sweetness',
                nameTh: 'ความหวาน',
                calculateType: 'NO',
                choices: [
                    {
                        id: '1',
                        name: 'No Sweet',
                        nameTh: 'ไม่หวาน',
                        price: 0,
                        default: false,
                    },
                    {
                        id: '2',
                        name: 'Less Sweet',
                        nameTh: 'หวานน้อย',
                        price: 0,
                        default: false,
                    },
                    {
                        id: '3',
                        name: 'Normal',
                        nameTh: 'หวานปกติ',
                        price: 0,
                        default: true,
                    },
                    {
                        id: '4',
                        name: 'Extra Sweet',
                        nameTh: 'หวานมาก',
                        price: 0,
                        default: false,
                    },
                ],
            },
            {
                id: '3',
                type: 'SINGLE',
                name: 'additionalShot',
                nameTh: 'จำนวน shot กาแฟ',
                calculateType: 'ADDITIONAL',
                choices: [
                    {
                        id: '1',
                        name: 'NO',
                        nameTh: 'ไม่เพิ่ม',
                        price: 0,
                        default: true,
                    },
                    {
                        id: '2',
                        name: 'เพิ่ม 1 Shot',
                        nameTh: 'เพิ่ม 1 Shot',
                        price: 10,
                        default: false,
                    },
                ],
            },
        ],
    },
    {
        id: '6',
        name: 'dalgona',
        nameTh: 'ดัลโกน่า',
        categoryName: 'กาแฟร่วมสมัย',
        imageUrl: 'https://img.freepik.com/free-vector/coffee-love-foam-with-beans-cartoon-icon-illustration_138676-2575.jpg?t=st=1694105026~exp=1694105626~hmac=593436c074ea22bb01f82537139f071ce8907998b821c532d509dc1f45db8fd1',
        basePrice: 40,
        options: [
            {
                id: '1',
                type: 'SINGLE',
                name: 'process',
                nameTh: 'รูปแบบ',
                calculateType: 'BASE',
                choices: [
                    {
                        id: '1',
                        name: 'iced',
                        nameTh: 'เย็น',
                        price: 40,
                        default: true,
                    },
                ],
            },
        ],
    },
    {
        id: '7',
        name: 'caramel coffee',
        nameTh: 'คาราเมลคอฟฟี่',
        categoryName: 'กาแฟร่วมสมัย',
        imageUrl: 'https://img.freepik.com/free-vector/coffee-love-foam-with-beans-cartoon-icon-illustration_138676-2575.jpg?t=st=1694105026~exp=1694105626~hmac=593436c074ea22bb01f82537139f071ce8907998b821c532d509dc1f45db8fd1',
        basePrice: 40,
        options: [
            {
                id: '1',
                type: 'SINGLE',
                name: 'process',
                nameTh: 'รูปแบบ',
                calculateType: 'BASE',
                choices: [
                    {
                        id: '1',
                        name: 'iced',
                        nameTh: 'เย็น',
                        price: 40,
                        default: true,
                    },
                ],
            },
        ],
    },
    {
        id: '8',
        name: 'latte brown sugar',
        nameTh: 'ลาเต้บราวน์ชูการ์',
        categoryName: 'กาแฟร่วมสมัย',
        imageUrl: 'https://img.freepik.com/free-vector/coffee-love-foam-with-beans-cartoon-icon-illustration_138676-2575.jpg?t=st=1694105026~exp=1694105626~hmac=593436c074ea22bb01f82537139f071ce8907998b821c532d509dc1f45db8fd1',
        basePrice: 40,
        options: [
            {
                id: '1',
                type: 'SINGLE',
                name: 'process',
                nameTh: 'รูปแบบ',
                calculateType: 'BASE',
                choices: [
                    {
                        id: '1',
                        name: 'iced',
                        nameTh: 'เย็น',
                        price: 40,
                        default: true,
                    },
                ],
            },
        ],
    },
    {
        id: '9',
        name: 'orange coffee',
        nameTh: 'กาแฟส้ม',
        categoryName: 'กาแฟร่วมสมัย',
        imageUrl: 'https://img.freepik.com/free-vector/coffee-love-foam-with-beans-cartoon-icon-illustration_138676-2575.jpg?t=st=1694105026~exp=1694105626~hmac=593436c074ea22bb01f82537139f071ce8907998b821c532d509dc1f45db8fd1',
        basePrice: 40,
        options: [
            {
                id: '1',
                type: 'SINGLE',
                name: 'process',
                nameTh: 'รูปแบบ',
                calculateType: 'BASE',
                choices: [
                    {
                        id: '1',
                        name: 'iced',
                        nameTh: 'เย็น',
                        price: 40,
                        default: true,
                    },
                ],
            },
            {
                id: '2',
                type: 'SINGLE',
                name: 'sweetness',
                nameTh: 'ความหวาน',
                calculateType: 'NO',
                choices: [
                    {
                        id: '1',
                        name: 'Less Sweet',
                        nameTh: 'หวานน้อย',
                        price: 0,
                        default: false,
                    },
                    {
                        id: '2',
                        name: 'Normal',
                        nameTh: 'หวานปกติ',
                        price: 0,
                        default: true,
                    },
                    {
                        id: '3',
                        name: 'Extra Sweet',
                        nameTh: 'หวานมาก',
                        price: 0,
                        default: false,
                    },
                ],
            },
            {
                id: '3',
                type: 'SINGLE',
                name: 'additionalShot',
                nameTh: 'จำนวน shot กาแฟ',
                calculateType: 'ADDITIONAL',
                choices: [
                    {
                        id: '1',
                        name: 'NO',
                        nameTh: 'ไม่เพิ่ม',
                        price: 0,
                        default: true,
                    },
                    {
                        id: '2',
                        name: 'เพิ่ม 1 Shot',
                        nameTh: 'เพิ่ม 1 Shot',
                        price: 10,
                        default: false,
                    },
                ],
            },
        ],
    },
    {
        id: '10',
        name: 'lychee cpffee',
        nameTh: 'กาแฟลิ้นจี่',
        categoryName: 'กาแฟร่วมสมัย',
        imageUrl: 'https://img.freepik.com/free-vector/coffee-love-foam-with-beans-cartoon-icon-illustration_138676-2575.jpg?t=st=1694105026~exp=1694105626~hmac=593436c074ea22bb01f82537139f071ce8907998b821c532d509dc1f45db8fd1',
        basePrice: 40,
        options: [
            {
                id: '1',
                type: 'SINGLE',
                name: 'process',
                nameTh: 'รูปแบบ',
                calculateType: 'BASE',
                choices: [
                    {
                        id: '1',
                        name: 'iced',
                        nameTh: 'เย็น',
                        price: 40,
                        default: true,
                    },
                ],
            },
            {
                id: '2',
                type: 'SINGLE',
                name: 'sweetness',
                nameTh: 'ความหวาน',
                calculateType: 'NO',
                choices: [
                    {
                        id: '1',
                        name: 'Less Sweet',
                        nameTh: 'หวานน้อย',
                        price: 0,
                        default: false,
                    },
                    {
                        id: '2',
                        name: 'Normal',
                        nameTh: 'หวานปกติ',
                        price: 0,
                        default: true,
                    },
                    {
                        id: '3',
                        name: 'Extra Sweet',
                        nameTh: 'หวานมาก',
                        price: 0,
                        default: false,
                    },
                ],
            },
            {
                id: '3',
                type: 'SINGLE',
                name: 'additionalShot',
                nameTh: 'จำนวน shot กาแฟ',
                calculateType: 'ADDITIONAL',
                choices: [
                    {
                        id: '1',
                        name: 'NO',
                        nameTh: 'ไม่เพิ่ม',
                        price: 0,
                        default: true,
                    },
                    {
                        id: '2',
                        name: 'เพิ่ม 1 Shot',
                        nameTh: 'เพิ่ม 1 Shot',
                        price: 10,
                        default: false,
                    },
                ],
            },
        ],
    },
    {
        id: '11',
        name: 'coconut coffe',
        nameTh: 'กาแฟมะพร้าว',
        categoryName: 'กาแฟร่วมสมัย',
        imageUrl: 'https://img.freepik.com/free-vector/coffee-love-foam-with-beans-cartoon-icon-illustration_138676-2575.jpg?t=st=1694105026~exp=1694105626~hmac=593436c074ea22bb01f82537139f071ce8907998b821c532d509dc1f45db8fd1',
        basePrice: 40,
        options: [
            {
                id: '1',
                type: 'SINGLE',
                name: 'process',
                nameTh: 'รูปแบบ',
                calculateType: 'BASE',
                choices: [
                    {
                        id: '1',
                        name: 'iced',
                        nameTh: 'เย็น',
                        price: 40,
                        default: true,
                    },
                ],
            },
            {
                id: '2',
                type: 'SINGLE',
                name: 'sweetness',
                nameTh: 'ความหวาน',
                calculateType: 'NO',
                choices: [
                    {
                        id: '1',
                        name: 'Less Sweet',
                        nameTh: 'หวานน้อย',
                        price: 0,
                        default: false,
                    },
                    {
                        id: '2',
                        name: 'Normal',
                        nameTh: 'หวานปกติ',
                        price: 0,
                        default: true,
                    },
                    {
                        id: '3',
                        name: 'Extra Sweet',
                        nameTh: 'หวานมาก',
                        price: 0,
                        default: false,
                    },
                ],
            },
            {
                id: '3',
                type: 'SINGLE',
                name: 'additionalShot',
                nameTh: 'จำนวน shot กาแฟ',
                calculateType: 'ADDITIONAL',
                choices: [
                    {
                        id: '1',
                        name: 'NO',
                        nameTh: 'ไม่เพิ่ม',
                        price: 0,
                        default: true,
                    },
                    {
                        id: '2',
                        name: 'เพิ่ม 1 Shot',
                        nameTh: 'เพิ่ม 1 Shot',
                        price: 10,
                        default: false,
                    },
                ],
            },
        ],
    },
    {
        id: '12',
        name: 'cocoa',
        nameTh: 'โกโก้',
        categoryName: 'เครื่องดื่มเย็น',
        imageUrl: 'https://img.freepik.com/free-vector/coffee-love-foam-with-beans-cartoon-icon-illustration_138676-2575.jpg?t=st=1694105026~exp=1694105626~hmac=593436c074ea22bb01f82537139f071ce8907998b821c532d509dc1f45db8fd1',
        basePrice: 40,
        options: [
            {
                id: '1',
                type: 'SINGLE',
                name: 'process',
                nameTh: 'รูปแบบ',
                calculateType: 'BASE',
                choices: [
                    {
                        id: '1',
                        name: 'hot',
                        nameTh: 'ร้อน',
                        price: 30,
                        default: false,
                    },
                    {
                        id: '2',
                        name: 'iced',
                        nameTh: 'เย็น',
                        price: 40,
                        default: true,
                    },
                    {
                        id: '3',
                        name: 'frappe',
                        nameTh: 'ปั่น',
                        price: 45,
                        default: false,
                    },
                ],
            },
            {
                id: '2',
                type: 'SINGLE',
                name: 'sweetness',
                nameTh: 'ความหวาน',
                calculateType: 'NO',
                choices: [
                    {
                        id: '1',
                        name: 'No Sweet',
                        nameTh: 'ไม่หวาน',
                        price: 0,
                        default: false,
                    },
                    {
                        id: '2',
                        name: 'Less Sweet',
                        nameTh: 'หวานน้อย',
                        price: 0,
                        default: false,
                    },
                    {
                        id: '3',
                        name: 'Normal',
                        nameTh: 'หวานปกติ',
                        price: 0,
                        default: true,
                    },
                    {
                        id: '4',
                        name: 'Extra Sweet',
                        nameTh: 'หวานมาก',
                        price: 0,
                        default: false,
                    },
                ],
            },
        ],
    },
    {
        id: '13',
        name: 'pink milk',
        nameTh: 'นมชมพู',
        categoryName: 'เครื่องดื่มเย็น',
        imageUrl: 'https://img.freepik.com/free-vector/coffee-love-foam-with-beans-cartoon-icon-illustration_138676-2575.jpg?t=st=1694105026~exp=1694105626~hmac=593436c074ea22bb01f82537139f071ce8907998b821c532d509dc1f45db8fd1',
        basePrice: 40,
        options: [
            {
                id: '1',
                type: 'SINGLE',
                name: 'process',
                nameTh: 'รูปแบบ',
                calculateType: 'BASE',
                choices: [
                    {
                        id: '1',
                        name: 'iced',
                        nameTh: 'เย็น',
                        price: 40,
                        default: true,
                    },
                    {
                        id: '2',
                        name: 'frappe',
                        nameTh: 'ปั่น',
                        price: 45,
                        default: false,
                    },
                ],
            },
            {
                id: '2',
                type: 'SINGLE',
                name: 'sweetness',
                nameTh: 'ความหวาน',
                calculateType: 'NO',
                choices: [
                    {
                        id: '2',
                        name: 'Less Sweet',
                        nameTh: 'หวานน้อย',
                        price: 0,
                        default: false,
                    },
                    {
                        id: '3',
                        name: 'Normal',
                        nameTh: 'หวานปกติ',
                        price: 0,
                        default: true,
                    },
                    {
                        id: '4',
                        name: 'Extra Sweet',
                        nameTh: 'หวานมาก',
                        price: 0,
                        default: false,
                    },
                ],
            },
        ],
    },
    {
        id: '14',
        name: 'green tea',
        nameTh: 'ชาเขียว',
        categoryName: 'ชา',
        imageUrl: 'https://img.freepik.com/free-vector/coffee-love-foam-with-beans-cartoon-icon-illustration_138676-2575.jpg?t=st=1694105026~exp=1694105626~hmac=593436c074ea22bb01f82537139f071ce8907998b821c532d509dc1f45db8fd1',
        basePrice: 40,
        options: [
            {
                id: '1',
                type: 'SINGLE',
                name: 'process',
                nameTh: 'รูปแบบ',
                calculateType: 'BASE',
                choices: [
                    {
                        id: '1',
                        name: 'iced',
                        nameTh: 'เย็น',
                        price: 40,
                        default: true,
                    },
                    {
                        id: '2',
                        name: 'frappe',
                        nameTh: 'ปั่น',
                        price: 45,
                        default: false,
                    },
                ],
            },
            {
                id: '2',
                type: 'SINGLE',
                name: 'sweetness',
                nameTh: 'ความหวาน',
                calculateType: 'NO',
                choices: [
                    {
                        id: '1',
                        name: 'No Sweet',
                        nameTh: 'ไม่หวาน',
                        price: 0,
                        default: false,
                    },
                    {
                        id: '2',
                        name: 'Less Sweet',
                        nameTh: 'หวานน้อย',
                        price: 0,
                        default: false,
                    },
                    {
                        id: '3',
                        name: 'Normal',
                        nameTh: 'หวานปกติ',
                        price: 0,
                        default: true,
                    },
                    {
                        id: '4',
                        name: 'Extra Sweet',
                        nameTh: 'หวานมาก',
                        price: 0,
                        default: false,
                    },
                ],
            },
        ],
    },
    {
        id: '15',
        name: 'thai tea',
        nameTh: 'ชาไทย',
        categoryName: 'ชา',
        imageUrl: 'https://img.freepik.com/free-vector/coffee-love-foam-with-beans-cartoon-icon-illustration_138676-2575.jpg?t=st=1694105026~exp=1694105626~hmac=593436c074ea22bb01f82537139f071ce8907998b821c532d509dc1f45db8fd1',
        basePrice: 40,
        options: [
            {
                id: '1',
                type: 'SINGLE',
                name: 'process',
                nameTh: 'รูปแบบ',
                calculateType: 'BASE',
                choices: [
                    {
                        id: '1',
                        name: 'hot',
                        nameTh: 'ร้อน',
                        price: 30,
                        default: false,
                    },
                    {
                        id: '2',
                        name: 'iced',
                        nameTh: 'เย็น',
                        price: 40,
                        default: true,
                    },
                    {
                        id: '3',
                        name: 'frappe',
                        nameTh: 'ปั่น',
                        price: 45,
                        default: false,
                    },
                ],
            },
            {
                id: '2',
                type: 'SINGLE',
                name: 'sweetness',
                nameTh: 'ความหวาน',
                calculateType: 'NO',
                choices: [
                    {
                        id: '1',
                        name: 'No Sweet',
                        nameTh: 'ไม่หวาน',
                        price: 0,
                        default: false,
                    },
                    {
                        id: '2',
                        name: 'Less Sweet',
                        nameTh: 'หวานน้อย',
                        price: 0,
                        default: false,
                    },
                    {
                        id: '3',
                        name: 'Normal',
                        nameTh: 'หวานปกติ',
                        price: 0,
                        default: true,
                    },
                    {
                        id: '4',
                        name: 'Extra Sweet',
                        nameTh: 'หวานมาก',
                        price: 0,
                        default: false,
                    },
                ],
            },
        ],
    },
    {
        id: '16',
        name: 'lemon tea',
        nameTh: 'ชามะนาว',
        categoryName: 'ชา',
        imageUrl: 'https://img.freepik.com/free-vector/coffee-love-foam-with-beans-cartoon-icon-illustration_138676-2575.jpg?t=st=1694105026~exp=1694105626~hmac=593436c074ea22bb01f82537139f071ce8907998b821c532d509dc1f45db8fd1',
        basePrice: 45,
        options: [
            {
                id: '1',
                type: 'SINGLE',
                name: 'process',
                nameTh: 'รูปแบบ',
                calculateType: 'BASE',
                choices: [
                    {
                        id: '1',
                        name: 'iced',
                        nameTh: 'เย็น',
                        price: 45,
                        default: true,
                    },
                ],
            },
            {
                id: '2',
                type: 'SINGLE',
                name: 'sweetness',
                nameTh: 'ความหวาน',
                calculateType: 'NO',
                choices: [
                    {
                        id: '1',
                        name: 'No Sweet',
                        nameTh: 'ไม่หวาน',
                        price: 0,
                        default: false,
                    },
                    {
                        id: '2',
                        name: 'Less Sweet',
                        nameTh: 'หวานน้อย',
                        price: 0,
                        default: false,
                    },
                    {
                        id: '3',
                        name: 'Normal',
                        nameTh: 'หวานปกติ',
                        price: 0,
                        default: true,
                    },
                    {
                        id: '4',
                        name: 'Extra Sweet',
                        nameTh: 'หวานมาก',
                        price: 0,
                        default: false,
                    },
                ],
            },
        ],
    },
    {
        id: '17',
        name: 'lemon green tea',
        nameTh: 'ชาเขียวมะนาว',
        categoryName: 'ชา',
        imageUrl: 'https://img.freepik.com/free-vector/coffee-love-foam-with-beans-cartoon-icon-illustration_138676-2575.jpg?t=st=1694105026~exp=1694105626~hmac=593436c074ea22bb01f82537139f071ce8907998b821c532d509dc1f45db8fd1',
        basePrice: 45,
        options: [
            {
                id: '1',
                type: 'SINGLE',
                name: 'process',
                nameTh: 'รูปแบบ',
                calculateType: 'BASE',
                choices: [
                    {
                        id: '1',
                        name: 'iced',
                        nameTh: 'เย็น',
                        price: 45,
                        default: true,
                    },
                ],
            },
            {
                id: '2',
                type: 'SINGLE',
                name: 'sweetness',
                nameTh: 'ความหวาน',
                calculateType: 'NO',
                choices: [
                    {
                        id: '1',
                        name: 'No Sweet',
                        nameTh: 'ไม่หวาน',
                        price: 0,
                        default: false,
                    },
                    {
                        id: '2',
                        name: 'Less Sweet',
                        nameTh: 'หวานน้อย',
                        price: 0,
                        default: false,
                    },
                    {
                        id: '3',
                        name: 'Normal',
                        nameTh: 'หวานปกติ',
                        price: 0,
                        default: true,
                    },
                    {
                        id: '4',
                        name: 'Extra Sweet',
                        nameTh: 'หวานมาก',
                        price: 0,
                        default: false,
                    },
                ],
            },
        ],
    },
    {
        id: '18',
        name: 'ice',
        nameTh: 'น้ำแข็ง',
        categoryName: 'อื่นๆ',
        imageUrl: 'https://img.freepik.com/free-vector/coffee-love-foam-with-beans-cartoon-icon-illustration_138676-2575.jpg?t=st=1694105026~exp=1694105626~hmac=593436c074ea22bb01f82537139f071ce8907998b821c532d509dc1f45db8fd1',
        basePrice: 5,
        options: [
            {
                id: '1',
                type: 'SINGLE',
                name: 'Size',
                nameTh: 'ขนาด',
                calculateType: 'BASE',
                choices: [
                    {
                        id: '1',
                        name: 'S',
                        nameTh: 'แก้วเล็ก',
                        price: 5,
                        default: true,
                    },
                    {
                        id: '2',
                        name: 'M',
                        nameTh: 'แก้วกลาง',
                        price: 10,
                        default: false,
                    },
                    {
                        id: '3',
                        name: 'L',
                        nameTh: 'แก้วใหญ่',
                        price: 15,
                        default: false,
                    },
                ],
            },
        ],
    },
    {
        id: '19',
        name: 'custom menu',
        nameTh: 'เมนูสั่งทำ',
        categoryName: 'อื่นๆ',
        imageUrl: 'https://img.freepik.com/free-vector/coffee-love-foam-with-beans-cartoon-icon-illustration_138676-2575.jpg?t=st=1694105026~exp=1694105626~hmac=593436c074ea22bb01f82537139f071ce8907998b821c532d509dc1f45db8fd1',
        basePrice: 5,
        options: [
            {
                id: '1',
                type: 'SINGLE',
                name: 'price',
                nameTh: 'ราคา',
                calculateType: 'BASE',
                choices: [
                    {
                        id: '1',
                        name: '',
                        nameTh: '',
                        price: 5,
                        default: false,
                    },
                    {
                        id: '2',
                        name: '',
                        nameTh: '',
                        price: 10,
                        default: true,
                    },
                    {
                        id: '3',
                        name: '',
                        nameTh: '',
                        price: 15,
                        default: false,
                    },
                    {
                        id: '4',
                        name: '',
                        nameTh: '',
                        price: 20,
                        default: false,
                    },
                    {
                        id: '5',
                        name: '',
                        nameTh: '',
                        price: 25,
                        default: false,
                    },
                    {
                        id: '6',
                        name: '',
                        nameTh: '',
                        price: 30,
                        default: false,
                    },
                    {
                        id: '7',
                        name: '',
                        nameTh: '',
                        price: 35,
                        default: false,
                    },
                    {
                        id: '8',
                        name: '',
                        nameTh: '',
                        price: 40,
                        default: true,
                    },
                    {
                        id: '9',
                        name: '',
                        nameTh: '',
                        price: 45,
                        default: false,
                    },
                    {
                        id: '10',
                        name: '',
                        nameTh: '',
                        price: 50,
                        default: false,
                    },
                    {
                        id: '11',
                        name: '',
                        nameTh: '',
                        price: 55,
                        default: false,
                    },
                    {
                        id: '12',
                        name: '',
                        nameTh: '',
                        price: 60,
                        default: false,
                    },
                ],
            },
        ],
    },
];